# Generated by Django 3.1.6 on 2021-02-06 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210204_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='auther',
            new_name='author',
        ),
    ]
